apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-a-hpa
  namespace: microservices
  labels:
    app: svc-a
    version: "1.0.0"
    managed-by: kubectl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-a
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
