apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: microservices
  labels:
    app: svc-a
    version: "1.0.0"
    managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: svc-a
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
