apiVersion: v1
kind: Service
metadata:
  name: svc-d
  namespace: microservices
  labels:
    app: svc-d
    version: "1.0.0"
    managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: svc-d
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
