apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices
  labels:
    app: db-credentials
    managed-by: kubectl
type: Opaque
data:
  DB_USERNAME: cGxhY2Vob2xkZXI=
  DB_PASSWORD: cGxhY2Vob2xkZXI=
