apiVersion: v1
kind: Service
metadata:
  name: svc-c
  namespace: microservices
  labels:
    app: svc-c
    version: "1.0.0"
    managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: svc-c
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
